# name: l10n_gen
# description: A sample command-line application.
# version: 1.0.0
# # repository: https://github.com/my_org/my_repo

# # Add regular dependencies here.
# dependencies:
#   path: ^1.9.0

# dev_dependencies:
#   lints: ^6.0.0
#   test: ^1.25.6

name: l10n_gen
description: CLI to generate Flutter ARB files and config from Dart variables.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  l10n_gen: main

dependencies:
  analyzer: ^6.0.0
  path: ^1.8.0
  http: ^1.1.0
  translator: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
