# name: l10n_gen
# description: A sample command-line application.
# version: 1.0.0
# # repository: https://github.com/my_org/my_repo

# # Add regular dependencies here.
# dependencies:
#   path: ^1.9.0

# dev_dependencies:
#   lints: ^6.0.0
#   test: ^1.25.6

name: easy_l10n_gen
description: CLI to generate Flutter ARB files and config from Dart variables.
version: 1.0.3
repository: https://github.com/abhaysaqi/easy_l10n_gen

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  easy_l10n_gen: main

dependencies:
  analyzer: ^10.0.2
  path: ^1.9.1
  http: ^1.6.0
  translator: ^1.0.4

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
